# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red) "

# Disable the AWS module.
[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
ssh_only = false
disabled = false
style = "bold italic #6808E1"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #4C33FF"

[cmd_duration]
min_time = 30
show_milliseconds = false
disabled = false
#prefix = " ⏲️   "
style = "bold italic #87A752"
