# new windows should open on current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
#
# # mouse wheel scrolls terminal history
# setw -g mouse on
#
# #### section
# #### inspired by https://github.com/tmux-plugins/tmux-sensible/blob/master/sensible.tmux
# set-option -s escape-time 0
#
# set-option -g history-limit 50000
#
# set-option -g display-time 4000
#
# set-option -g status-interval 5
#
# set-option -s default-terminal "screen-256color"
#
# # emacs key bindings in tmux command prompt (prefix + :) are better than
# # vi keys, even for vim users
# set-option -g status-keys emacs
#
# # focus events enabled for terminals that support them
# set-option -g focus-events on
#
# # super useful when using "grouped sessions" and multi-monitor setup
# set-window-option -g aggressive-resize on
#
# # easier switching between next/prev window
# # if key_binding_not_set "C-p"; then
# # 	tmux bind-key C-p previous-window
# # fi
# # 	tmux bind-key C-n next-window
# # fi
#
# bind-key R run-shell " \
# 	tmux source-file ${tmux_config} > /dev/null; \
# 	tmux display-message 'Sourced ${tmux_config}!'"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Improve Copy Mode with Tmux Yank
set -g @plugin 'tmux-plugins/tmux-yank'

# Enable mouse control
set -g mouse on

# mouse wheel scrolls terminal history
setw -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Allow applications like Vim to use OSC 52 to copy to the system clipboard
set -s set-clipboard on
set -as terminal-features ',xterm*:clipboard'
# Required for tmux 3.3a+
set -g allow-passthrough on

# Use vim keybindings in copy mode
setw -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane

# Make `y` copy the selected text, not exiting the copy mode. For copy-and-exit
# use ordinary `Enter`
bind -T copy-mode-vi y send-keys -X copy-pipe  # Only copy, no cancel
