#https://www.acarg.ch/posts/aerc-email-setup/

[rcpassosme]
source        = maildir://~/Mail/rcpassosme/
outgoing      = smtps://rafael%40rcpassos.me@smtp.purelymail.com:465
outgoing-cred-cmd = "gpg --no-tty --quiet --decrypt ~/.msmtp-pass.gpg"
default       = INBOX
folders-sort  = INBOX
postpone      = Drafts
cache-headers = true
from           = Rafael Passos <rafael@rcpassos.me>
check-mail-cmd = 'mbsync -c ~/.config/isync/mbsync.conf primary'
check-mail-timeout = 120s
check-mail    = 1m
copy-to       = Sent
cache-headers = true

# [rcpassosme]
# source        = imaps://rafael%40rcpassos.me@imap.purelymail.com:993
# outgoing      = smtps://rafael%40rcpassos.me@smtp.purelymail.com:465
# default       = INBOX
# from          = Rafael Passos <rafael@rcpassos.me>
# copy-to   outgoing-cred-cmd    = Sent
# cache-headers = true

# [ime-usp]
# source         = maildir://~/Mail/imeusp
# outgoing       = smtps://rcpassos%40ime.usp.br@smtp.pass.com:465
# #default        = INBOX
# from           = Rafael Passos <rcpassos@ime.usp.br>
# check-mail-cmd = 'mbsync -c ~/.config/isync/mbsync.conf imeusp'
# check-mail-timeout = 120s 
# check-mail    = 1m
# copy-to       = Sent
# cache-headers = true
