CopyArrivalDate yes
Create Near
Expunge Both

IMAPAccount rcpassosme
Host imap.purelymail.com
Port 993
User rafael@rcpassos.me
PassCmd "gpg --no-tty --quiet --decrypt ~/.msmtp-pass.gpg"
TLSType IMAPS

MaildirStore local
Path ~/Mail/rcpassosme/
Inbox ~/Mail/rcpassosme/INBOX
SubFolders Verbatim

IMAPStore rcpassosme
Account rcpassosme

Channel primary
Far :rcpassosme:
Near :local:
Patterns *


#imeusp
# IMAPAccount imeusp
# Host imap.gmail.com
# Port 993
# User rcpassos@ime.usp.br
# PassCmd "gpg --no-tty --quiet --decrypt ~/.msmtp-usp-pass.gpg"
# TLSType IMAPS
# AuthMechs LOGIN
#
# MaildirStore imeusp_local
# Path ~/Mail/imeusp/
# Inbox ~/Mail/imeusp/INBOX
# SubFolders Verbatim
#
# IMAPStore imeusp
# Account imeusp
#
# Channel imeusp
# Far :imeusp:
# Near :imeusp_local:
# # Patterns *
# Patterns * !"[Gmail]/All Mail" !"[Gmail]/Important" !"[Gmail]/Starred" !"[Gmail]/Bin"
